codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: auto
        threshold: 2% # Allow 2% decrease
        informational: false

    patch:
      default:
        target: 80% # New code should have 80% coverage
        informational: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  web:
    paths:
      - web/src/
    carryforward: true

  worker:
    paths:
      - worker/src/
    carryforward: true
